version: '{build}'
image: Visual Studio 2017
install:
- cmd: >-
    curl -O https://download.microsoft.com/download/0/F/D/0FD852A4-7EA1-4E2A-983A-0484AC19B92C/dotnet-sdk-2.0.0-win-x64.exe
    
    dotnet-sdk-2.0.0-win-x64.exe /install /quiet /norestart /log install.log
    
build_script:
- cmd: >-
    "C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start
    
    Nake.bat APPVEYOR=True package
test: off
artifacts:
- path: Output\*.nupkg
